build_libobjc2.sh
build_libdispatch.sh
build_make.sh
build_gnustep-base.sh
build_gnustep-gui.sh
build_gnustep-back.sh
../nextspace/Packaging/Sources/7_build_Frameworks.sh
../nextspace/Packaging/Sources/8_build_Applications.sh
../nextspace/Packaging/Sources/9_install_scripts.sh
../nextspace/Packaging/Sources/apply-patches.sh
../nextspace/Packaging/Sources/download-sources.sh
../nextspace/Packaging/Sources/versions.inc.sh
